language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    
script: "./gradlew build"
notifications:
  slack: wundermusik:4eXUNFk7VqfdCedotyRZpQWn
